# [은하계 분류 - 기계학습 6주차](https://www.kaggle.com/c/2021-ml-p4)
> 17011520 조영래

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import ADASYN
from sklearn.preprocessing import StandardScaler, LabelEncoder
from itertools import product

RANDOM_STATE = 42

In [ ]:
file_path = '/content/drive/MyDrive/2021-1/기계학습(최유경)/6/2021-ml-p4/'

X_train = pd.read_csv(file_path + 'train_desc_pca.csv')
y_train = pd.read_csv(file_path + 'train_label.csv')
X_test = pd.read_csv(file_path + 'test_desc_pca.csv')
sample_submit = pd.read_csv(file_path + 'sample_submit.csv')

## 데이터 확인

In [ ]:
X_train.shape, X_test.shape

((6000, 64), (1500, 64))

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 64 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       6000 non-null   float64
 1   1       6000 non-null   float64
 2   2       6000 non-null   float64
 3   3       6000 non-null   float64
 4   4       6000 non-null   float64
 5   5       6000 non-null   float64
 6   6       6000 non-null   float64
 7   7       6000 non-null   float64
 8   8       6000 non-null   float64
 9   9       6000 non-null   float64
 10  10      6000 non-null   float64
 11  11      6000 non-null   float64
 12  12      6000 non-null   float64
 13  13      6000 non-null   float64
 14  14      6000 non-null   float64
 15  15      6000 non-null   float64
 16  16      6000 non-null   float64
 17  17      6000 non-null   float64
 18  18      6000 non-null   float64
 19  19      6000 non-null   float64
 20  20      6000 non-null   float64
 21  21      6000 non-null   float64
 22  

In [ ]:
X_train.head()

0          1          2  ...        61        62        63
0  13.934082  -3.077109 -13.515020  ...  0.530720  0.171594 -0.322960
1  18.757893  -0.304454   1.757282  ...  1.700099 -0.001509  1.077432
2  -8.063476  -3.259291 -16.577340  ...  2.724299 -0.663966 -1.755266
3   3.128894  16.911400 -10.434631  ...  0.440074 -0.087064  1.925870
4 -15.744248  -1.022630   0.004898  ... -2.284629  0.672590 -0.606422

[5 rows x 64 columns]

In [ ]:
X_train.describe()

0             1  ...            62            63
count  6000.000000  6.000000e+03  ...  6.000000e+03  6.000000e+03
mean     -0.000001  2.977292e-07  ...  5.184532e-08 -5.473566e-07
std      15.160195  1.175099e+01  ...  1.145874e+00  1.122422e+00
min     -29.148262 -3.459106e+01  ... -6.133607e+00 -4.392254e+00
25%     -13.018061 -7.919902e+00  ... -7.237511e-01 -7.356384e-01
50%      -1.814440  4.529633e-01  ...  3.809234e-03 -1.324568e-02
75%      12.306866  8.088094e+00  ...  7.377873e-01  7.273624e-01
max      44.900420  4.437014e+01  ...  7.029471e+00  5.139948e+00

[8 rows x 64 columns]

In [ ]:
# ID 는 drop해야될듯
y_train.head()

Id Category
0   0     edge
1   1     edge
2   2     edge
3   3     edge
4   4     edge

In [ ]:
 y_train = y_train.drop('Id', axis=1)
 y_train.head()

Category
0     edge
1     edge
2     edge
3     edge
4     edge

In [ ]:
y_train.value_counts()

Category
spiral      2000
smooth      2000
edge        2000
dtype: int64

In [ ]:
le_y = LabelEncoder()
y_train = le_y.fit_transform(y_train)
pd.unique(y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2])

## standard scaling

In [ ]:
std_scaler = StandardScaler()
std_scaler.fit(X_train)

X_train_std = std_scaler.transform(X_train)
X_test_std = std_scaler.transform(X_test)

## 하이퍼파라미터 조정 X

### std scaling -> X

In [ ]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_train_pred = lr.predict(X_train)
print(accuracy_score(y_train, y_train_pred))

0.8045


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
confusion_matrix(y_train, y_train_pred)

array([[1756,  150,   94],
       [ 121, 1609,  270],
       [ 157,  381, 1462]])

### std scaling -> O

In [ ]:
lr_std = LogisticRegression()
lr_std.fit(X_train_std, y_train)

y_train_std_pred = lr_std.predict(X_train_std)
print(accuracy_score(y_train, y_train_std_pred))

0.8046666666666666


In [ ]:
confusion_matrix(y_train, y_train_std_pred)

array([[1755,  151,   94],
       [ 120, 1610,  270],
       [ 157,  380, 1463]])

In [ ]:
lr_std.intercept_

array([-0.53455722,  0.04603305,  0.48852416])

In [ ]:
lr_std.coef_

array([[ 4.58606977e-01, -4.13675477e-01, -2.29471348e+00,
        -2.65206665e-01, -1.27184602e-01, -2.94597333e-01,
         6.63548326e-02, -1.76904338e-02,  3.79140473e-01,
         3.72546123e-01, -3.31170846e-01,  2.57792515e-01,
         3.57650596e-02, -6.29623883e-02, -2.67502862e-01,
        -2.65463452e-01,  2.27282248e-01, -2.04053811e-01,
         3.09582023e-01,  7.25525920e-02, -1.67007366e-01,
         2.42056438e-01, -3.61037279e-02,  2.82342081e-01,
         1.41709371e-01, -1.81184770e-01,  2.09606793e-01,
        -4.97767314e-02, -8.01848926e-02,  1.55565110e-01,
         5.66973935e-03, -5.29116567e-02,  7.51146409e-02,
        -1.68719689e-01,  1.72669404e-01, -1.39707005e-01,
        -2.04027710e-01, -1.58719661e-02,  7.42746147e-02,
        -4.56350961e-02, -3.63553530e-03,  3.47409419e-02,
        -2.40671116e-02, -2.08048206e-02, -8.61764055e-03,
        -4.04567525e-02,  1.04336499e-01, -1.01748836e-02,
        -1.87900049e-01, -1.10995997e-02,  1.25306773e-0

### 제출데이터 생성

In [ ]:
sample_submit.head()

Id Category
0   0     none
1   1     none
2   2     none
3   3     none
4   4     none

In [ ]:
y_test_pred = lr_std.predict(X_test_std)
y_test_pred_inv = le_y.inverse_transform(y_test_pred)
sample_submit['Category'] = y_test_pred_inv
sample_submit.to_csv('submission.csv', index=False)

## 하이퍼파라미터 조정해보기

In [ ]:
def search_params(model, params, metric, X, y, verbose=True):
  print(f'<<<{model.__class__}>>>')
  
  score_with_params = []
  param_names = params.keys()
  X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                      stratify=y,
                                                      random_state=RANDOM_STATE)

  for param in product(*params.values()):
    param_dict = dict(zip(param_names, param))
    model.set_params(**param_dict)
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    train_metric = metric(y_train, y_train_pred)
    test_metric = metric(y_test, y_test_pred)
    
    if verbose:
      print(f'##### {param_dict} #####')
      print(f'train {metric.__class__}: {train_metric}')
      print(f'test {metric.__class__}: {test_metric}')
      print('\n')

    score_with_params.append((train_metric, test_metric, param_dict))

  return score_with_params

In [ ]:
params = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['saga']
}

In [ ]:
accuracy_with_params = search_params(LogisticRegression(), params, accuracy_score,
                                     X_train_std, y_train, verbose=False)

<<<<class 'sklearn.linear_model._logistic.LogisticRegression'>>>>


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [ ]:
for accuracy_params in sorted(accuracy_with_params,
                              reverse=True,
                              key= lambda x: x[1])[:10]:
  print(accuracy_params)

(0.8051111111111111, 0.7806666666666666, {'penalty': 'l2', 'C': 0.1, 'solver': 'saga'})
(0.8068888888888889, 0.7793333333333333, {'penalty': 'l1', 'C': 1, 'solver': 'saga'})
(0.8057777777777778, 0.7793333333333333, {'penalty': 'l2', 'C': 1, 'solver': 'saga'})
(0.8073333333333333, 0.7786666666666666, {'penalty': 'l1', 'C': 0.1, 'solver': 'saga'})
(0.8053333333333333, 0.7786666666666666, {'penalty': 'l1', 'C': 10, 'solver': 'saga'})
(0.8055555555555556, 0.7786666666666666, {'penalty': 'l1', 'C': 100, 'solver': 'saga'})
(0.8053333333333333, 0.7786666666666666, {'penalty': 'l2', 'C': 0.01, 'solver': 'saga'})
(0.8055555555555556, 0.7786666666666666, {'penalty': 'l2', 'C': 10, 'solver': 'saga'})
(0.8055555555555556, 0.7786666666666666, {'penalty': 'l2', 'C': 100, 'solver': 'saga'})
(0.7984444444444444, 0.7686666666666667, {'penalty': 'l2', 'C': 0.001, 'solver': 'saga'})


In [ ]:
# submission 만드는 함수
# params : (n_parameters, )의 형태로 dict 형태로 parameter 들어있음

def submission_by_params(model, params, X, y, test, submission, file_name_prefix='submission'):
  for param in params:
    model.set_params(**param)
    model.fit(X, y)
    
    y_pred = model.predict(test)
    y_pred_inv = le_y.inverse_transform(y_pred)
    sample_submit['Category'] = y_pred_inv
    
    file_name = f'{file_name_prefix}_{param}.csv'
    sample_submit.to_csv(file_name, index=False)

In [ ]:
submission_params = [x[2] for x in sorted(accuracy_with_params, 
                                          reverse=True,
                                          key= lambda x: x[1])[:10]]

In [ ]:
submission_by_params(LogisticRegression(),
                     submission_params,
                     X_train_std, y_train, X_test_std, 
                     sample_submit,
                     file_name_prefix='std_submission')

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


### 점수 확인

|penalty|C|solver|score|
|-|-|-|-|
|l2|0.1|saga|0.79533|
|l1|1|saga|0.79666|
|l2|1|saga|0.79533|



보기용 하이퍼파라미터별 validation 셋 점수
```
(0.8051111111111111, 0.7806666666666666, {'penalty': 'l2', 'C': 0.1, 'solver': 'saga'})
(0.8068888888888889, 0.7793333333333333, {'penalty': 'l1', 'C': 1, 'solver': 'saga'})
(0.8057777777777778, 0.7793333333333333, {'penalty': 'l2', 'C': 1, 'solver': 'saga'})
(0.8073333333333333, 0.7786666666666666, {'penalty': 'l1', 'C': 0.1, 'solver': 'saga'})
(0.8053333333333333, 0.7786666666666666, {'penalty': 'l1', 'C': 10, 'solver': 'saga'})
(0.8055555555555556, 0.7786666666666666, {'penalty': 'l1', 'C': 100, 'solver': 'saga'})
(0.8053333333333333, 0.7786666666666666, {'penalty': 'l2', 'C': 0.01, 'solver': 'saga'})
(0.8055555555555556, 0.7786666666666666, {'penalty': 'l2', 'C': 10, 'solver': 'saga'})
(0.8055555555555556, 0.7786666666666666, {'penalty': 'l2', 'C': 100, 'solver': 'saga'})
(0.7984444444444444, 0.7686666666666667, {'penalty': 'l2', 'C': 0.001, 'solver': 'saga'})

```